name: build-deploy-staging

on:
  push:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v2.0.0
        with:
          version: 1.22.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-cache-

      # Uncomment the next line if you need to use a secret to create a .env file
      # - name: Create .env file from secret
      #   run: echo '${{ secrets.ENV_FILE }}' | base64 -d > .env

      - name: Install dependencies
        run: yarn

      - name: Build Next.js app
        run: yarn build
